
x-common: &common
  platform: linux/amd64      
  volumes:
      - clusterscratch:/scratch
      - ./etc/slurm.conf:/etc/slurm-llnl/slurm.conf
      - slurmnodeconfig:/etc/slurm-llnl/nodes
#            - ./etc/sssd.conf:/etc/sssd/sssd.conf
      - clusterhome:/home
      - ./etc/sshd_sssd.conf:/etc/ssh/sshd_config.d/sssd.conf
      - hostkeys:/etc/ssh/keys
      - software:/cluster/software
      - ./etc/spack/profile_spack_modules.sh:/etc/profile.d/spack-modules.sh
      - ./test:/opt/test
      - ./bin/docker-entrypoint-common.sh:/docker-entrypoint-common.sh
      - ./bin/docker-entrypoint-login.sh:/docker-entrypoint-login.sh
      - ./bin/docker-entrypoint-slurm.sh:/docker-entrypoint-slurm.sh
      - ./bin/docker-entrypoint-compute.sh:/docker-entrypoint-compute.sh
      - clusterstate:/state
      - slurmlog:/var/log/slurm-llnl
  restart: unless-stopped
  depends_on:
      - lldap
  environment:
      - LLDAP_DEFAULT_AUTH_TOKEN=${LLDAP_DEFAULT_AUTH_TOKEN?}

services:
    login:
      <<: *common
      hostname: login
      build:
        target: login
      ports:
      - "${SSH_PORT:-2022}:22"
    slurm:
      <<: *common
      hostname: slurm
      build:
        target: slurm
    compute01:
      <<: *common
      hostname: compute01
      build:
        target: compute

    lldap:
        image: lldap/lldap:stable
        ports:
            # For LDAP, not recommended to expose, see Usage section.
            #- "3890:3890"
            # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
            #- "6360:6360"
            # For the web front-end
            - "127.0.0.1:17170:17170"
        volumes:
            - "lldap_data:/data"
            - "./bootstrap:/bootstrap"
            - "./bin/setup.sh:/setup.sh"
            # Alternatively, you can mount a local folder
            # - "./lldap_data:/data"
        restart: unless-stopped
        environment:
            - UID=1000
            - GID=1000
            - TZ=Europe/London
            - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET?}
            - LLDAP_KEY_SEED=${LLDAP_KEY_SEED?}
            - LLDAP_LDAP_BASE_DN=dc=royce-hpc-training,dc=org
            - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS?}
            - LLDAP_ADMIN_PASSWORD=${LLDAP_LDAP_USER_PASS?}
            # If using LDAPS, set enabled true and configure cert and key path
            # - LLDAP_LDAPS_OPTIONS__ENABLED=true
            # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
            # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
            # You can also set a different database:
            # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
            # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
            # If using SMTP, set the following variables
            # - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
            # - LLDAP_SMTP_OPTIONS__SERVER=smtp.example.com
            # - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp provider's documentation for this setting
            # - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
            # - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
            # - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
            # - LLDAP_SMTP_OPTIONS__FROM=no-reply <no-reply@example.com> # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
            # - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.
        post_start:
          - command: /setup.sh
            user: root
            environment:
              - LLDAP_DEFAULT_AUTH_TOKEN=${LLDAP_DEFAULT_AUTH_TOKEN?}

    spack:
      platform: linux/amd64
      image: spack/ubuntu-focal:1.0.1
      volumes:
        - software:/cluster/software
        - ./etc/spack/config.yaml:/opt/spack/etc/spack/config.yaml
        - ./etc/spack/modules.yaml:/opt/spack/etc/spack/modules.yaml
        - ./etc/spack/envs:/opt/spack/envs
        - ./etc/spack/setup.sh:/opt/spack/setup.sh
      environment:
        - GITHUB_TOKEN_PACKAGE_WRITE=${GITHUB_TOKEN_PACKAGE_WRITE:-}

volumes:
    clusterstate:
    clusterscratch:
    clusterhome:
    hostkeys:
    lldap_data:
    software:
    slurmnodeconfig:
    slurmlog:
