[sssd]
config_file_version = 2
domains = LDAP
services = nss, pam

[domain/LDAP]
id_provider = ldap
auth_provider = ldap
cache_credentials = true
ldap_uri = ldaps://ldap.manchester.ac.uk/
ldap_search_base = ou=uman,o=ac,c=uk
ldap_group_member = cn

override_gid = 100
case_sensitive = false
ldap_tls_reqcert = never
